Medic Class Reference
#include <Medic.h>
Public Member Functions
Medic (int Id, std::string role, std::string password, std::string username, std::string specialty)
std::unique_ptr< User > clone (int id, std::string role, std::string password, std::string username, std::string specialty) const
void setState (std::string newState)
std::string getState ()
void addAppointmentInfo ()
std::string getSpecialty () const
void showMenu () const
~Medic ()
Public Member Functions inherited from User
User (int id, std::string role, std::string password, std::string username)
virtual int getId () const
virtual std::string getRole () const
virtual std::string getPassword () const
virtual std::string getUsername () const
~User ()
Private Attributes
std::unique_ptr< Agenda > medicAgenda
std::string specialty
std::string medicState
Detailed Description
Definition at line 9 of file Medic.h.
Constructor & Destructor Documentation
Medic()
Medic::Medic (int Id, std::string role, std::string password, std::string username, std::string specialty)
Definition at line 3 of file Medic.cpp.
    : User(id, role, password, username){
        this->specialty = specialty;
    }
References specialty.
~Medic()
Medic::~Medic ()
Definition at line 72 of file Medic.cpp.
             {
}
Member Function Documentation
addAppointmentInfo()
void Medic::addAppointmentInfo ()
Definition at line 20 of file Medic.cpp.
{}
clone()
std::unique_ptr< User > Medic::clone (int id, std::string role, std::string password, std::string username, std::string specialty) const [inline], [virtual]
Implements User.
Definition at line 17 of file Medic.h.
                                                                                                                        {
        return std::make_unique<Medic> (id, role, password, username, specialty);
    }
References User::password, User::role, specialty, and User::username.
getSpecialty()
std::string Medic::getSpecialty () const
Definition at line 16 of file Medic.cpp.
                                   {
    return specialty;
}
References specialty.
Referenced by main().
getState()
std::string Medic::getState ()
Definition at line 12 of file Medic.cpp.
                         {
    return medicState;
}
References medicState.
setState()
void Medic::setState (std::string newState)
Definition at line 8 of file Medic.cpp.
                                      {
    medicState = newState;
}
References medicState.
showMenu()
void Medic::showMenu () const
Definition at line 22 of file Medic.cpp.
                           {
    system("clear");
    int userSelection;
    std::cout << "=== Menu Medic ===\n"
    << "1. Confirmar Asistencia.\n"
    << "2. Modificar Agenda.\n"
    << "3. Añadir Notas a Cita.\n"
    << "4. Volver.\n"
    << "Seleccione una opción: ";
    std::cin >> userSelection;
    switch (userSelection)
    {
    case 1:
        std::cout << "Funcion no implementada. Presiona Enter para continuar...\n";
        std::cin.ignore();
        std::cin.get();
        showMenu();
        break;
    case 2:
        std::cout << "Funcion no implementada. Presiona Enter para continuar...\n";
        std::cin.ignore();
        std::cin.get();
        showMenu();
        break;
    
    case 3:
        std::cout << "Funcion no implementada. Presiona Enter para continuar...\n";
        std::cin.ignore();
        std::cin.get();
        showMenu();
        break;
        break;
    case 4:
        return;
        
    default:
        std::cout << "Selecione una opccion valida. Presiona Enter para continuar...\n";
        std::cin.ignore();
        std::cin.get();
        showMenu();
        break;
    }
}
References showMenu().
Referenced by main(), and showMenu().
Member Data Documentation
medicAgenda
std::unique_ptr<Agenda> Medic::medicAgenda [private]
Definition at line 12 of file Medic.h.
medicState
std::string Medic::medicState [private]
Definition at line 14 of file Medic.h.
Referenced by getState(), and setState().
specialty
std::string Medic::specialty [private]
Definition at line 13 of file Medic.h.
Referenced by clone(), getSpecialty(), and Medic().
The documentation for this class was generated from the following files:
src/Medic.h
src/Medic.cpp