System Class Reference
Clase principal del sistema de gestión de citas.
#include <System.h>
Public Member Functions
void addRobot (Robot &robot)
Añade un robot a la cola de robots del sistema.
Robot * getRobotFront ()
Obtiene el primer robot de la cola.
void printAvailableRobots ()
Muestra los robots disponibles.
void accompany (int time)
Asigna un robot libre para acompañar.
std::unique_ptr< User > login (sqlite3 *db)
Realiza el proceso de inicio de sesión.
sqlite3 * getDb () const
Devuelve el puntero a la base de datos.
void registerNewUser (sqlite3 *db)
Registra un nuevo usuario en el sistema.
void openDb ()
Abre la base de datos del sistema.
System (System &otherSystem)=delete
Constructor de copia eliminado.
void operator= (const System &)=delete
Operador de asignación eliminado.
void showMedicsList (sqlite3 *db)
Muestra la lista de médicos registrados.
void createMedic (sqlite3 *db)
Asigna una especialidad a un médico.
void assignScheduleToMedic (sqlite3 *db)
Asigna un horario a un médico.
void updateScheduleForMedic (sqlite3 *db, int medicId, std::string start, std::string end)
Actualiza el horario de un médico.
int verifyMedic (sqlite3 *db, int medicId)
Verifica que un usuario sea médico.
void showAppointments ()
Muestra las citas del sistema.
~System ()
Destructor del sistema.
Static Public Member Functions
static System * getTheSystem ()
Devuelve la instancia única del sistema.
static std::unique_ptr< User > makeUser (int id, std::string role, std::string password, std::string username, std::string specialty)
Crea un usuario dinámicamente según su rol.
Protected Member Functions
System ()
Constructor protegido.
Private Attributes
std::queue< Robot * > robots
Cola de robots del sistema.
sqlite3 * db
Puntero a la base de datos SQLite.
Static Private Attributes
static System * singleSystem = nullptr
Instancia única del sistema (Singleton).
Detailed Description
Clase principal del sistema de gestión de citas.
La clase System implementa el patrón Singleton y se encarga de:
Gestionar la conexión con la base de datos SQLite.
Controlar el inicio de sesión y registro de usuarios.
Crear usuarios según su rol (Admin, Medic, Patient).
Administrar robots disponibles para acompañamiento.
Gestionar médicos y sus horarios.
Definition at line 27 of file System.h.
Constructor & Destructor Documentation
System() [1/2]
System::System () [inline], [protected]
Constructor protegido.
Evita la creación directa de instancias fuera de la clase, garantizando el uso del patrón Singleton.
Definition at line 56 of file System.h.
{};
Referenced by getTheSystem().
System() [2/2]
System::System (System & otherSystem) [delete]
Constructor de copia eliminado.
Evita la copia de la instancia Singleton.
~System()
System::~System ()
Destructor del sistema.
Libera los recursos y cierra la base de datos.
Definition at line 175 of file System.cpp.
               {
    sqlite3_close(db); // close the db
}
References db.
Member Function Documentation
accompany()
void System::accompany (int time)
Asigna un robot libre para acompañar.
Parameters
time Tiempo durante el cual el robot acompañará.
Definition at line 63 of file System.cpp.
                              {
    if(robots.front()->getState() == "Libre"){
        Robot* tempRobot = robots.front();
        robots.pop();
        tempRobot->dummy(time);
        robots.push(tempRobot);}
    
    else{std::cout << "There are no free robots, wait until one is available and select an option.\n";}
}
References Robot::dummy(), and robots.
Referenced by robotAcompanySim().
addRobot()
void System::addRobot (Robot & robot)
Añade un robot a la cola de robots del sistema.
Parameters
robot Robot que se desea añadir.
Definition at line 34 of file System.cpp.
                                 {
    robots.push(&robot);
}
References robots.
Referenced by robotAcompanySim().
assignScheduleToMedic()
void System::assignScheduleToMedic (sqlite3 * db)
Asigna un horario a un médico.
_ATTACHMENT :
Parameters
db Puntero a la base de datos SQLite.
Definition at line 271 of file System.cpp.
                                             {
    // Primero, mostrar las medicos disponibles.
    showMedicsList(db);
    int medicId;
    std::string start;
    std::string end;
    std::cout << "Introduce el ID del Medico: ";
    std::cin >> medicId;
    if(verifyMedic(db, medicId)== 1){
        return;
    }
    std::cout << "Introduce la hora de inicio: ";
    std::cin >> start;
    std::cout << "Introduce la hora de fin: ";
    std::cin >> end;
    // Sentencia preparada con parámetros
    const char* sql = "INSERT INTO SCHEDULE (ID_DOCTOR, START, END) VALUES (?, ?, ?);";
    sqlite3_stmt* stmt;
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
    if (rc != SQLITE_OK) {
        std::cerr << "Error al preparar la sentencia: " << sqlite3_errmsg(db) << std::endl;
        sqlite3_close(db);
        return;
    }
    // Enlazar los valores
    sqlite3_bind_int(stmt, 1, medicId);
    sqlite3_bind_text(stmt, 2, start.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 3, end.c_str(), -1, SQLITE_TRANSIENT);
    char ans;
    // Ejecutar
    rc = sqlite3_step(stmt);
    
    if (rc != SQLITE_DONE) {
        //std::cerr << "Error al insertar horario: " << sqlite3_errmsg(db) << std::endl;
        if (std::string(sqlite3_errmsg(db)).find("FOREIGN KEY") != std::string::npos) {
            std::cerr << "El medico con ID " << medicId << " no existe." << std::endl;
        }
        if (std::string(sqlite3_errmsg(db)).find("UNIQUE") != std::string::npos) {
            std::cerr << "El medico con ID " << medicId << " ya tiene un horario asignado. ¿Quieres actualizarlo? (s/n)" << std::endl;
            std::cin >> ans;
            if(ans == 's'){
                updateScheduleForMedic(db, medicId, start, end);
            }
        }
    } else {
        std::cout << "Horario insertado correctamente.\n";
        std::cout << "ID del Medico: " << sqlite3_last_insert_rowid(db) << std::endl;
    }
    sqlite3_finalize(stmt);
}
References db, showMedicsList(), updateScheduleForMedic(), and verifyMedic().
Referenced by AssingSchedule::execute().
createMedic()
void System::createMedic (sqlite3 * db)
Asigna una especialidad a un médico.
Parameters
db Puntero a la base de datos SQLite.
Definition at line 226 of file System.cpp.
                                   {
    showMedicsList(db);
    std::string specialty;
    int id;
    std::cout << "Seleciona un medico por ID: ";
    std::cin >> id;
    if(verifyMedic(db, id) == 1){
        return;
    }
    std::cout << "Introduce su especialidad: ";
    std::cin >> specialty;
    // Sentencia preparada con parámetros
    const char* sql = "UPDATE USER SET SPECIALTY = ? WHERE ID = ?;"; // Solo cambia la del usuario 5;
    sqlite3_stmt* stmt;
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
    if (rc != SQLITE_OK) {
        std::cerr << "Error al preparar la sentencia: " << sqlite3_errmsg(db) << std::endl;
        sqlite3_close(db);
        return;
    }
    // Enlazar los valores
    sqlite3_bind_text(stmt, 1, specialty.c_str(), -1, SQLITE_TRANSIENT); // Nueva contraseña
    sqlite3_bind_int(stmt, 2, id); // ID del usuario
    // Ejecutar
    rc = sqlite3_step(stmt);
    if (rc != SQLITE_DONE) {
        std::cerr << "Error al insertar especialidad: " << sqlite3_errmsg(db) << std::endl;
    } else {
        std::cout << "Especialidad asignada correctamente al medico con ID: " << id << "\n";
    }
    // Liberar
    sqlite3_finalize(stmt);
    return;
}
References db, showMedicsList(), and verifyMedic().
Referenced by MakeDoctorCommand::execute().
getDb()
sqlite3 * System::getDb () const
Devuelve el puntero a la base de datos.
Returns
Puntero sqlite3 activo.
Definition at line 119 of file System.cpp.
                            {
    return db;
}
References db.
Referenced by AssingSchedule::execute(), MakeDoctorCommand::execute(), ViewDoctorList::execute(), and main().
getRobotFront()
Robot * System::getRobotFront ()
Obtiene el primer robot de la cola.
Returns
Puntero al primer robot disponible.
Definition at line 38 of file System.cpp.
                            {
    if (robots.empty()) {
        std::cout << "No robots available";
    }
    return robots.front();
}
References robots.
getTheSystem()
System * System::getTheSystem () [static]
Devuelve la instancia única del sistema.
Si no existe, se crea una nueva instancia.
Returns
Puntero a la instancia única de System.
Definition at line 5 of file System.cpp.
                            {
    if (singleSystem == nullptr){
        singleSystem = new System ();
    }
    else{
        std::cout << "Error: trying to get another instance of a System singleton class!\n";
    }
    return singleSystem;
}
References singleSystem, and System().
Referenced by main().
login()
std::unique_ptr< User > System::login (sqlite3 * db)
Realiza el proceso de inicio de sesión.
Solicita las credenciales del usuario y las verifica en la base de datos.
Parameters
db Puntero a la base de datos SQLite.
Returns
Usuario autenticado.
Exceptions
DatabaseError Si ocurre un error al acceder a la base de datos.
InvalidCredentialsError Si las credenciales son incorrectas.
Definition at line 73 of file System.cpp.
                                            { // login function
    std::string usernameToVerify, passwordToVerify;
    std::cout << "Ingrese el username: ";
    std::cin >> usernameToVerify;
    std::cout << "Ingrese la contraseña: ";
    std::cin >> passwordToVerify;
    // sql sentence
    const char* sql = "SELECT ID, USERNAME, PASSWORD, ROLE, SPECIALTY FROM USER WHERE username = ? AND password = ?;";
    sqlite3_stmt* stmt;
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        throw DatabaseError(sqlite3_errmsg(db));
    }
    // link the values
    sqlite3_bind_text(stmt, 1, usernameToVerify.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 2, passwordToVerify.c_str(), -1, SQLITE_TRANSIENT);
    int id;
    std::string username;
    std::string password;
    std::string role;
    std::string specialty;
    if ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        id = sqlite3_column_int(stmt, 0);
        username = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 1));
        password = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 2));
        role = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 3));
        specialty = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 4));
        return makeUser(id, role, username, password, specialty);
    }
    else{
        throw InvalidCredentialsError();
    }
    sqlite3_finalize(stmt);
    return nullptr;
}
References db, and makeUser().
Referenced by main().
makeUser()
std::unique_ptr< User > System::makeUser (int id, std::string role, std::string password, std::string username, std::string specialty) [static]
Crea un usuario dinámicamente según su rol.
Implementa el patrón Prototype para instanciar el tipo correcto de usuario.
Parameters
id Identificador del usuario.
role Rol del usuario (Admin, Medic o Patient).
password Contraseña del usuario.
username Nombre de usuario.
specialty Especialidad del médico (si aplica).
Returns
Puntero inteligente a un objeto User.
Definition at line 181 of file System.cpp.
                                                                                                                         {
    std::map<std::string, User*> userType = {
    {"Admin", new Admin(0, "", "", "", "")},
    {"Medic", new Medic(0, "", "", "", "")},
    {"Patient", new Patient(0, "", "", "", "")}
    };
    return userType[role]->clone(id, role, password, username, specialty);
}
References Patient::clone().
Referenced by login().
openDb()
void System::openDb ()
Abre la base de datos del sistema.
Inicializa la conexión con SQLite y configura las restricciones de claves foráneas.
Exceptions
DatabaseError Si ocurre un error al abrir la base de datos.
Definition at line 16 of file System.cpp.
                   {
    int rc;
    // Abrir la base de datos
    rc = sqlite3_open("appointment_system.db", &db);
    if (rc) {
        throw DatabaseError(sqlite3_errmsg(db));
    }
    const char* pragma_sql = "PRAGMA foreing_keys = ON;";
    
    if (rc !=SQLITE_OK) {
        throw DatabaseError(sqlite3_errmsg(db));
    }
    rc = sqlite3_exec(db, pragma_sql, 0, 0, 0);
}
References db.
Referenced by main().
operator=()
void System::operator= (const System &) [delete]
Operador de asignación eliminado.
Evita la asignación de instancias Singleton.
printAvailableRobots()
void System::printAvailableRobots ()
Muestra los robots disponibles.
Imprime por pantalla los robots cuyo estado sea "Libre".
Definition at line 45 of file System.cpp.
                                 {
    if (robots.front()->getState() != "Libre") {
        std::cout << "No robots available.\n";
        return;
    }
    
    std::queue<Robot*> temp = robots; // Copia
    
    while (!temp.empty()) {
        Robot* robot = temp.front(); // Obtener el robot
        
        if (robot->getState() == "Libre") {
            std::cout << *robot << "\n";
        }
        temp.pop();
    }
}
References Robot::getState(), and robots.
Referenced by robotAcompanySim().
registerNewUser()
void System::registerNewUser (sqlite3 * db)
Registra un nuevo usuario en el sistema.
Inserta un nuevo usuario en la base de datos.
Parameters
db Puntero a la base de datos SQLite.
Exceptions
DatabaseError Si ocurre un error durante la inserción.
Definition at line 123 of file System.cpp.
                                        { // Function to register a new user, requires de bd
    std::string name;
    std::string password;
    std::string role;
    std::string specialty = "";
    std::cout << "Introduce el usuario: ";
    std::cin >> name;
    std::cout << "Introduce la contraseña: ";
    std::cin >> password;
    bool validRole = false;
    while(!validRole) {
        std::cout << "Introduce el tipo (Patient, Medic o Admin): ";
        std::cin >> role;
        
        if(role == "Patient" || role == "Medic" || role == "Admin") {
            validRole = true;
        } else {
            std::cout << "Rol inválido. Debe ser Patient, Medic o Admin.\n";
        }
    }
    // Sentencia preparada con parámetros
    const char* sql = "INSERT INTO USER (USERNAME, PASSWORD, ROLE, SPECIALTY) VALUES (?, ?, ?, ?);";
    sqlite3_stmt* stmt;
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
    if (rc != SQLITE_OK) {
        throw DatabaseError(sqlite3_errmsg(db));
    }
    // Enlazar los valores
    sqlite3_bind_text(stmt, 1, name.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 2, password.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 3, role.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 4, specialty.c_str(), -1, SQLITE_TRANSIENT);
    // Ejecutar
    rc = sqlite3_step(stmt);
    if (rc != SQLITE_DONE) {
        throw DatabaseError(sqlite3_errmsg(db));
    } else {
        std::cout << "Datos insertados correctamente.\n";
    }
    // Liberar
    sqlite3_finalize(stmt);
}
References db.
Referenced by main().
showAppointments()
void System::showAppointments ()
Muestra las citas del sistema.
Funcionalidad pendiente de implementación.
Definition at line 388 of file System.cpp.
                             {
    std::cout << "funcion no implementada\n";
}
Referenced by ViewAppointments::execute().
showMedicsList()
void System::showMedicsList (sqlite3 * db)
Muestra la lista de médicos registrados.
Parameters
db Puntero a la base de datos SQLite.
Definition at line 190 of file System.cpp.
                                      {
    const char* sql;
    sql = "SELECT ID, USERNAME, PASSWORD, ROLE, SPECIALTY FROM USER WHERE role = 'Medic';";
    sqlite3_stmt* stmt;
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        std::cerr << "Error al preparar la consulta: " << sqlite3_errmsg(db) << std::endl;
        sqlite3_close(db);
        return;
    }
    int id;
    std::string username;
    std::string password;
    std::string role;
    std::string specialty;
    std::cout << "=== Lista de Medicos ===\n";
    while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        
        id = sqlite3_column_int(stmt, 0);
        username = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 1));
        password = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 2));
        role = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 3));
        specialty = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 4));
        std::cout << "id: " << id << " - " << "username: " << username << " - " << "password: " << password << " - " << "role: " << role << " - " << "especialidad: " << specialty << "\n";
    }
    sqlite3_finalize(stmt);
}
References db.
Referenced by assignScheduleToMedic(), createMedic(), and ViewDoctorList::execute().
updateScheduleForMedic()
void System::updateScheduleForMedic (sqlite3 * db, int medicId, std::string start, std::string end)
Actualiza el horario de un médico.
Parameters
db Puntero a la base de datos SQLite.
medicId Identificador del médico.
start Hora de inicio.
end Hora de fin.
Definition at line 333 of file System.cpp.
                                                                                            {
    
    const char* sql = "UPDATE SCHEDULE SET START = ?, END = ? WHERE ID_DOCTOR = ?;";
    sqlite3_stmt* stmt;
    
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
    if (rc != SQLITE_OK) {
        std::cerr << "Error al preparar actualización: " << sqlite3_errmsg(db) << std::endl;
        return;
    }
    
    sqlite3_bind_text(stmt, 1, start.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 2, end.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_int(stmt, 3, medicId);
    
    rc = sqlite3_step(stmt);
    if (rc != SQLITE_DONE) {
        std::cerr << "Error al actualizar horario: " << sqlite3_errmsg(db) << std::endl;
    } else {
        std::cout << "Horario actualizado correctamente.\n";
    }
    
    sqlite3_finalize(stmt);
}
References db.
Referenced by assignScheduleToMedic().
verifyMedic()
int System::verifyMedic (sqlite3 * db, int medicId)
Verifica que un usuario sea médico.
Parameters
db Puntero a la base de datos SQLite.
medicId Identificador del usuario.
Returns
0 si el usuario es médico, 1 en caso contrario.
Definition at line 358 of file System.cpp.
                                               {
    // VERIFICAR QUE EL USUARIO SEA UN MÉDICO
    const char* checkRoleSql = "SELECT ROLE FROM USER WHERE ID = ?;";
    sqlite3_stmt* checkRoleStmt;
    int rc = sqlite3_prepare_v2(db, checkRoleSql, -1, &checkRoleStmt, NULL);
    if (rc != SQLITE_OK) {
        std::cerr << "Error al verificar rol: " << sqlite3_errmsg(db) << std::endl;
        return 1;
    }
    
    sqlite3_bind_int(checkRoleStmt, 1, medicId);
    rc = sqlite3_step(checkRoleStmt);
    
    if (rc != SQLITE_ROW) {
        std::cerr << "Error: El usuario con ID " << medicId << " no existe." << std::endl;
        sqlite3_finalize(checkRoleStmt);
        return 1;
    }
    
    std::string role = reinterpret_cast<const char*>(sqlite3_column_text(checkRoleStmt, 0));
    sqlite3_finalize(checkRoleStmt);
    
    if (role != "Medic") {
        std::cerr << "Error: El usuario con ID " << medicId
                  << " no es un medico. Es un " << role << "." << std::endl;
        return 1;
    }
    return 0;
}
References db.
Referenced by assignScheduleToMedic(), and createMedic().
Member Data Documentation
db
sqlite3* System::db [private]
Puntero a la base de datos SQLite.
Se utiliza para realizar todas las operaciones de persistencia.
Definition at line 42 of file System.h.
Referenced by assignScheduleToMedic(), createMedic(), getDb(), login(), openDb(), registerNewUser(), showMedicsList(), updateScheduleForMedic(), verifyMedic(), and ~System().
robots
std::queue<Robot*> System::robots [private]
Cola de robots del sistema.
Almacena punteros a robots y permite gestionarlos en orden FIFO.
Definition at line 35 of file System.h.
Referenced by accompany(), addRobot(), getRobotFront(), and printAvailableRobots().
singleSystem
System * System::singleSystem = nullptr [static], [private]
Instancia única del sistema (Singleton).
Definition at line 47 of file System.h.
Referenced by getTheSystem().
The documentation for this class was generated from the following files:
src/System.h
src/System.cpp