Patient Class Reference
#include <Patient.h>
Public Member Functions
Patient (int Id, std::string role, std::string password, std::string username)
bool getAppointmentState ()
std::string getAppointmentHistoryToString ()
void addAppointmentToHistory (Appointment &appointmentToAdd)
void setCurrentAppointment (std::unique_ptr< Appointment > appointment)
void showMenu () const
~Patient ()
Public Member Functions inherited from User
User (int id, std::string role, std::string password, std::string username)
int getId () const
virtual std::string getRole () const
std::string getPassword () const
std::string getUsername () const
~User ()
Private Attributes
std::unique_ptr< Appointment > currentAppointment
std::list< Appointment > appointmentHistory
Detailed Description
Definition at line 9 of file Patient.h.
Constructor & Destructor Documentation
Patient()
Patient::Patient (int Id, std::string role, std::string password, std::string username)
Definition at line 4 of file Patient.cpp.
    : User(id, role, password, username){
}
~Patient()
Patient::~Patient ()
Definition at line 48 of file Patient.cpp.
                 {
}
Member Function Documentation
addAppointmentToHistory()
void Patient::addAppointmentToHistory (Appointment & appointmentToAdd)
Definition at line 9 of file Patient.cpp.
                                                             {
    appointmentHistory.push_back(appointment);
}
References appointmentHistory.
getAppointmentHistoryToString()
std::string Patient::getAppointmentHistoryToString ()
getAppointmentState()
bool Patient::getAppointmentState ()
setCurrentAppointment()
void Patient::setCurrentAppointment (std::unique_ptr< Appointment > appointment)
Definition at line 13 of file Patient.cpp.
                                                                          {
    currentAppointment = std::move(appointment);
}
References currentAppointment.
showMenu()
void Patient::showMenu () const
Definition at line 17 of file Patient.cpp.
                             {
    system("clear");
    int userSelection;
    std::cout << "=== Menu Patient ===\n"
    << "1. Solicitar Cita.\n"
    << "2. Ver Mis Citas.\n"
    << "3. Volver.\n"
    << "Seleccione una opción: ";
    std::cin >> userSelection;
    switch (userSelection)
    {
    case 1:
        break;
    case 2:
        break;
    case 3:
        return;
        
    default:
        std::cout << "Selecione una opccion valida. Presiona Enter para continuar...\n";
        std::cin.ignore();
        std::cin.get();
        showMenu();
        break;
    }
}
References showMenu().
Referenced by main(), and showMenu().
Member Data Documentation
appointmentHistory
std::list<Appointment> Patient::appointmentHistory [private]
Definition at line 13 of file Patient.h.
Referenced by addAppointmentToHistory().
currentAppointment
std::unique_ptr<Appointment> Patient::currentAppointment [private]
Definition at line 12 of file Patient.h.
Referenced by setCurrentAppointment().
The documentation for this class was generated from the following files:
src/Patient.h
src/Patient.cpp